### ISSUE TITLE
Call registerSuite() from different cpp files

### ISSUE THREAD

**Issue by mondegreengames** [doe300/cpptest-lite#7]
I'd like to be able to run registerSuite() from different compilation units (to make it easier to have unit tests closer to the code they're testing), but if I #include "cpptest-main.h" in multiple files then I get linker errors saying that registerSuite() (and the other functions within) are already defined.
I can always create my own header that defines just registerSuite(), but is there an existing way to do what I want?

**Comment by doe300** [comment]
No, there is currently no (intended) existing way of achieving that.

The simplest solution would be forward-declare the function, e.g. via something like:

    namespace Test {
        void registerSuite(const std::function<Test::Suite*(void)>& supplier, const std::string& parameterName, const std::string& description = "", bool runByDefault = true);
    }

Optionally with the `extern` keyword.

Or as you said, redefine this function with a different name and the same behavior.
